// Generated by dojo-bindgen on Thu, 13 Jun 2024 13:28:34 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `dojo_starter::models::health::Health` model
public class Health : ModelInstance {
    [ModelField("entityId")]
    public FieldElement entityId;

    [ModelField("gameId")]
    public uint gameId;

    [ModelField("health")]
    public ushort health;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        